# Generated by Django 3.2.4 on 2021-06-23 19:18

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Bucket name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255, verbose_name='Bucket description')),
                ('is_public', models.BooleanField(default=True, help_text='Public buckets are listed in the main page so everyone know about their existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited buckets can grow up to a fixed number of members.', verbose_name='Is limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If a bucket is limited, this will be the limit on the number of members.', verbose_name='Members limit')),
                ('files_contained', models.PositiveIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-files_contained'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
